spring.application.name=todo-rest-api

spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=${PSQL_USERNAME}
spring.datasource.password=${PSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:certs/public.pem

server.port=8080

